package net.enderboy500.enderlib.util.interfaces;

import net.enderboy500.enderlib.helper.RegistryHelper;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.storage.loot.LootTable;

public interface VanillaChestLootTableList {
     ResourceKey<LootTable> ABANDONED_MINESHAFT = RegistryHelper.registerVanillaLootTable("chests/abandoned_mineshaft");
     ResourceKey<LootTable> ANCIENT_CITY = RegistryHelper.registerVanillaLootTable("chests/ancient_city");
     ResourceKey<LootTable> ANCIENT_CITY_ICE_BOX = RegistryHelper.registerVanillaLootTable("chests/ancient_city_ice_box");
     ResourceKey<LootTable> BASTION_BRIDGE = RegistryHelper.registerVanillaLootTable("chests/bastion_bridge");
     ResourceKey<LootTable> BASTION_HOGLIN_STABLE = RegistryHelper.registerVanillaLootTable("chests/bastion_hoglin_stable");
     ResourceKey<LootTable> BASTION_OTHER = RegistryHelper.registerVanillaLootTable("chests/bastion_other");
     ResourceKey<LootTable> BASTION_TREASURE = RegistryHelper.registerVanillaLootTable("chests/bastion_treasure");
     ResourceKey<LootTable> BURIED_TREASURE = RegistryHelper.registerVanillaLootTable("chests/buried_treasure");
     ResourceKey<LootTable> DESERT_PYRAMID = RegistryHelper.registerVanillaLootTable("chests/desert_pyramid");
     ResourceKey<LootTable> END_CITY = RegistryHelper.registerVanillaLootTable("chests/end_city_treasure");
     ResourceKey<LootTable> JUNGLE_TEMPLE = RegistryHelper.registerVanillaLootTable("chests/jungle_temple");
     ResourceKey<LootTable> JUNGLE_TEMPLE_DISPENSER = RegistryHelper.registerVanillaLootTable("chests/jungle_temple_dispenser");
     ResourceKey<LootTable> NETHER_FORTRESS = RegistryHelper.registerVanillaLootTable("chests/nether_bridge");
     ResourceKey<LootTable> PILLAGER_OUTPOST = RegistryHelper.registerVanillaLootTable("chests/pillager_outpost");
     ResourceKey<LootTable> RUINED_PORTAL = RegistryHelper.registerVanillaLootTable("chests/ruined_portal");
     ResourceKey<LootTable> SHIPWRECK_MAP = RegistryHelper.registerVanillaLootTable("chests/shipwreck_map");
     ResourceKey<LootTable> SHIPWRECK_SUPPLY = RegistryHelper.registerVanillaLootTable("chests/shipwreck_supply");
     ResourceKey<LootTable> SHIPWRECK_TREASURE = RegistryHelper.registerVanillaLootTable("chests/shipwreck_treasure");
     ResourceKey<LootTable> SIMPLE_DUNGEON = RegistryHelper.registerVanillaLootTable("chests/simple_dungeon");
     ResourceKey<LootTable> SPAWN_BONUS_CHEST = RegistryHelper.registerVanillaLootTable("chests/spawn_bonus_chest");
     ResourceKey<LootTable> STRONGHOLD_CORRIDOR = RegistryHelper.registerVanillaLootTable("chests/stronghold_corridor");
     ResourceKey<LootTable> STRONGHOLD_CROSSING = RegistryHelper.registerVanillaLootTable("chests/stronghold_crossing");
     ResourceKey<LootTable> STRONGHOLD_LIBRARY = RegistryHelper.registerVanillaLootTable("chests/stronghold_library");
     ResourceKey<LootTable> TRIAL_CHAMBER_CORRIDOR = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/corridor");
     ResourceKey<LootTable> TRIAL_CHAMBER_ENTRANCE = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/entrance");
     ResourceKey<LootTable> TRIAL_CHAMBER_INTERSECTION = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/intersection");
     ResourceKey<LootTable> TRIAL_CHAMBER_INTERSECTION_BARREL = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/intersection_barrel");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_COMMON = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_common");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_OMINOUS = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_ominous");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_OMINOUS_COMMON = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_ominous_common");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_OMINOUS_RARE = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_ominous_rare");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_OMINOUS_UNIQUE = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_ominous_unique");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_RARE = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_rare");
     ResourceKey<LootTable> TRIAL_CHAMBER_REWARD_UNIQUE = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/reward_unique");
     ResourceKey<LootTable> TRIAL_CHAMBER_SUPPLY = RegistryHelper.registerVanillaLootTable("chests/trial_chamber/supply");
     ResourceKey<LootTable> UNDERWATER_RUIN_BIG = RegistryHelper.registerVanillaLootTable("chests/underwater_ruin_big");
     ResourceKey<LootTable> UNDERWATER_RUIN_SMALL = RegistryHelper.registerVanillaLootTable("chests/underwater_ruin_small");
     ResourceKey<LootTable> VILLAGE_ARMORER = RegistryHelper.registerVanillaLootTable("chests/village/village_armorer");
     ResourceKey<LootTable> VILLAGE_BUTCHER = RegistryHelper.registerVanillaLootTable("chests/village/village_butcher");
     ResourceKey<LootTable> VILLAGE_CARTOGRAPHER = RegistryHelper.registerVanillaLootTable("chests/village/village_cartographer");
     ResourceKey<LootTable> VILLAGE_DESERT_HOUSE = RegistryHelper.registerVanillaLootTable("chests/village/village_desert_house");
     ResourceKey<LootTable> VILLAGE_FISHER = RegistryHelper.registerVanillaLootTable("chests/village/village_fisher");
     ResourceKey<LootTable> VILLAGE_FLETCHER = RegistryHelper.registerVanillaLootTable("chests/village/village_fletcher");
     ResourceKey<LootTable> VILLAGE_MASON = RegistryHelper.registerVanillaLootTable("chests/village/village_mason");
     ResourceKey<LootTable> VILLAGE_PLAINS_HOUSE = RegistryHelper.registerVanillaLootTable("chests/village/village_plains_house");
     ResourceKey<LootTable> VILLAGE_SAVANNA_HOUSE = RegistryHelper.registerVanillaLootTable("chests/village/village_savanna_house");
     ResourceKey<LootTable> VILLAGE_SHEPHERD = RegistryHelper.registerVanillaLootTable("chests/village/village_shepherd");
     ResourceKey<LootTable> VILLAGE_SNOWY_HOUSE = RegistryHelper.registerVanillaLootTable("chests/village/village_snowy_house");
     ResourceKey<LootTable> VILLAGE_TAIGA_HOUSE = RegistryHelper.registerVanillaLootTable("chests/village/village_taiga_house");
     ResourceKey<LootTable> VILLAGE_TANNERY = RegistryHelper.registerVanillaLootTable("chests/village/village_tannery");
     ResourceKey<LootTable> VILLAGE_TOOLSMITH = RegistryHelper.registerVanillaLootTable("chests/village/village_toolsmith");
     ResourceKey<LootTable> VILLAGE_WEAPONSMITH = RegistryHelper.registerVanillaLootTable("chests/village/village_weaponsmith");
     ResourceKey<LootTable> WOODLAND_MANSION = RegistryHelper.registerVanillaLootTable("chests/woodland_mansion");
}
